kvasaheim/urls.py
from django.urls import include, path
from . import views

app_name = 'kvasaheim'
urlpatterns = [
    path('', views.home, name='home'),
    path('logout', views.logout, name='logout'),
    path('<slug:title>', views.home, name='home'),
    path('category/<int:cpk>/', views.home, name='home'),
    path('realm/<int:rpk>/category/<int:cpk>/', views.home, name='home'),
    path('problem/<int:pk>/', views.problem_detail, name='problem_detail'),
    path('problem/<int:pk>/<int:ipk>/', views.problem_detail, name='problem_detail'),
    path('problem/<int:pk>/answer/<int:apk>/', views.problem_answer, name='problem_answer'),
    path('user/<str:user>/', views.user_profile, name='user_profile')
]

stats/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('', include('kvasaheim.urls', namespace='kvasaheim')),
]

kvasaheim/models.py
import ast
from random import randint
import string

from django.utils import timezone
from django.db import models

import numpy

def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]

class Realm(models.Model):
    title     = models.CharField(max_length=200, unique=True)
    text      = models.TextField()
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class Category(models.Model):
    title       = models.CharField(max_length=200, unique=True)
    published   = models.BooleanField(default=False)
    realm       = models.ForeignKey(Realm, on_delete=models.CASCADE,
                    related_name='category', related_query_name='categories')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "categories"

class Generator(models.Model):
    title          = models.CharField(max_length=200, blank=True)
    categorical    = models.BooleanField(default=False)
    random_low     = models.IntegerField(default=10)
    random_high    = models.IntegerField(default=100)
    num_rands_low  = models.PositiveIntegerField(default=5)
    num_rands_high = models.PositiveIntegerField(default=10)

    def __str__(self):
        if self.title:
            return self.title
        title = "Categorical Generator " if self.categorical else "Generator "
        title += str(self.pk)
        return title

class Problem(models.Model):
    title      = models.CharField(max_length=200, unique=True)
    text       = models.TextField()
    category   = models.ForeignKey(Category, on_delete=models.CASCADE,
                    related_name='problem', related_query_name='problems')
    published  = models.BooleanField(default=False)
    equation   = models.TextField(default="def solve(x):\n    return x")
    generators = models.ManyToManyField(Generator, symmetrical=False,
                    related_name='generator', related_query_name='generators')
    paths      = models.ManyToManyField('self', symmetrical=False,
                    related_name='path', related_query_name='path',
                    through='Path')
    formula    = models.TextField(default='<div style="margin:0 0 2em 2em;">')
    solution   = models.TextField()
    rcode      = models.TextField(default='<div class="r code">\n</div>')
    excel      = models.TextField(default='<div class="excel code">\n</div>')

    def __str__(self):
        return self.title

PATH_DEPENDS = 1
PATH_RECOMMENDS = 2
PATH_CHOICES = (
    (PATH_DEPENDS, 'Depends'),
    (PATH_RECOMMENDS, 'Recommends'),
)

class Path(models.Model):
    from_problem    = models.ForeignKey(Problem, on_delete=models.CASCADE,
                        related_name='from_problems',
                        related_query_name='from_problem')
    to_problem      = models.ForeignKey(Problem, on_delete=models.CASCADE,
                        related_name='to_problems',
                        related_query_name='to_problem')
    direction       = models.IntegerField(choices=PATH_CHOICES)

def generate_normal_list(num_rands_low, num_rands_high, random_low, random_high):
    num_rands = randint(num_rands_low, num_rands_high)
    loc = randint(random_low, random_high)
    scale = (loc - random_low) / 4
    numbers = list(numpy.random.normal(loc=loc,
        scale=scale, size=num_rands))
    return [int(n) for n in numbers]

class ProblemManager(models.Manager):
    def create_problem_instance(self, problem):
        numbers = None if len(problem.generators.all()) == 1 else '['
        count = 0
        categorical = False
        for generator in problem.generators.all():
            normal_list = generate_normal_list(generator.num_rands_low,
                            generator.num_rands_high, generator.random_low,
                            generator.random_high)
            if generator.categorical:
                categorical = True
                if numbers:
                    numbers += '['
                else:
                    numbers = '['
                for n in normal_list:
                    numbers += '"' + string.ascii_uppercase[n % 26] + '", '
                numbers = numbers[:-2]
                numbers += ']'
            else:
                if numbers:
                    numbers += str(normal_list)
                else:
                    numbers = str(normal_list)
            count += 1
            if count < len(problem.generators.all()):
                numbers += ', '
        if len(problem.generators.all()) > 1:
            numbers += ']'
        problem_instance = self.create(problem=problem, numbers=numbers,
                            lists=count, categorical=categorical,
                            answer_string=problem.equation)
        problem_instance.save()
        return problem_instance

class ProblemInstance(models.Model):
    problem       = models.ForeignKey(Problem, on_delete=models.CASCADE,
                    related_name='instances', related_query_name='instance')
    answer_string = models.TextField()
    numbers       = models.CharField(max_length=1000)
    lists         = models.PositiveIntegerField()
    categorical   = models.BooleanField()
    objects       = ProblemManager()

    @property
    def numbers_list(self):
        nlist = ast.literal_eval(self.numbers)
        return nlist

    @property
    def answer(self):
        answer = "" + self.answer_string
        exec(answer, globals())
        if (self.numbers != ''):
            return solve(self.numbers_list)
        else:
            return 0

    def __str__(self):
        return str(self.problem) + " " + str(self.id)

class Attempt(models.Model):
    problem = models.ForeignKey(ProblemInstance, on_delete=models.CASCADE,
                related_name='attempts', related_query_name='attempt')
    user    = models.ForeignKey('auth.user',
                related_name='attempts',  related_query_name='attempt',
                on_delete=models.SET(get_sentinel_user))
    answer  = models.CharField(max_length=200)
    date    = models.DateTimeField(default=timezone.now)

    @property
    def correct(self):
        if abs(self.problem.answer - float(self.answer)) < 0.001:
            return True
        return False

    def __str__(self):
        return "%s %s %s" % (self.user.username, self.problem,
            "Correct" if self.correct else "Incorrect")

kvasaheim/forms.py
from django import forms

class AnswerForm(forms.Form):
    answer = forms.DecimalField(label='Your guess:', decimal_places=4)
    problem_instance = forms.IntegerField(label='Problem Instance')

class CommentForm(forms.Form):
    text = forms.CharField(label='Comment', max_length=255,
    	widget=forms.Textarea)

kvasaheim/views.py
import string

from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.core.exceptions import PermissionDenied

from .forms import AnswerForm
from .models import Realm, Category, Problem, ProblemInstance, Attempt

def home(request, title=None, cpk=None):
    if title:
        realms = Realm.objects.filter(title=title, published=True)
    else:
        realms = Realm.objects.filter(published=True)
    if cpk:
        categories = Category.objects.filter(pk=cpk, published=True)
    else:
        categories = Category.objects.filter(published=True)
    problems = Problem.objects.filter(published=True)
    return render(request, 'kvasaheim/home.html',
        {'realms': realms, 'title': title, 'categories': categories, 'cpk': cpk,
        'problems': problems})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('kvasaheim:home'))

def problem_detail(request, pk, ipk=None):
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            nattempt = Attempt()
            nattempt.user = request.user
            nattempt.answer = form.cleaned_data['answer']
            nattempt.problem = get_object_or_404(ProblemInstance,
                pk=form.cleaned_data['problem_instance'])
            nattempt.save()
        return HttpResponseRedirect(reverse('kvasaheim:problem_answer',
         args=(pk, nattempt.id)))
    else:
        problem = get_object_or_404(Problem, pk=pk)
        form = AnswerForm()
        if ipk:
            instance = get_object_or_404(ProblemInstance, pk=ipk)
            if instance.problem != problem:
                raise Http404('No instance with that ID for this problem.')
        else:
            instance = ProblemInstance.objects.create_problem_instance(problem)
        list_sum = None
        if instance.lists > 1:
            for nlist in instance.numbers_list:
                if isinstance(nlist[0], int):
                    if list_sum:
                        list_sum = [list_sum] + sum(nlist)
                    else:
                        list_sum = sum(nlist)
        else:
            if isinstance(instance.numbers_list[0], int):
                list_sum = sum(instance.numbers_list)
        if problem.published:
            return render(request, 'kvasaheim/problem_detail.html',
                {'problem': problem, 'instance': instance,
                'form': form, 'list_sum': list_sum})
        else:
            raise PermissionDenied('Please log in.')

def problem_answer(request, pk, apk):
    if request.user.is_authenticated:
        problem = get_object_or_404(Problem, pk=pk)
        answer = get_object_or_404(Attempt, pk=apk)
        return render(request, 'kvasaheim/problem_answer.html',
            {'problem': problem, 'answer': answer,})
    else:
        raise PermissionDenied('Please log in.')

def user_profile(request, user):
    u = get_object_or_404(User, username=user)
    answers = Attempt.objects.filter(user=u).order_by('problem', 'date')
    categories = set()
    problems = set()
    for answer in answers:
        categories.add(Category.objects.get(problems=answer.problem.problem))
        problems.add(Problem.objects.get(instance=answer.problem))
    return render(request, 'kvasaheim/user_profile.html',
    {'u': u, 'categories': categories, 'problems': problems, 'answers': answers})

kvasaheim/templates/kvasaheim/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>{% block title %}{% endblock %}Sample Statistics</title>
    <!-- Fav Icons -->
    <link rel="apple-touch-icon" sizes="57x57" href="http://statistics.kvasaheim.com/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="http://statistics.kvasaheim.com/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="http://statistics.kvasaheim.com/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="http://statistics.kvasaheim.com/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="http://statistics.kvasaheim.com/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="http://statistics.kvasaheim.com/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="http://statistics.kvasaheim.com/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="http://statistics.kvasaheim.com/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="http://statistics.kvasaheim.com/apple-touch-icon-180x180.png">

    <link rel="icon" type="image/png" href="http://statistics.kvasaheim.com/favicon-16x16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="http://statistics.kvasaheim.com/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="http://statistics.kvasaheim.com/favicon-96x96.png" sizes="96x96">

    <link rel="icon" type="image/png" href="http://statistics.kvasaheim.com/android-chrome-192x192.png" sizes="192x192">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'kvasaheim/main.css' %}" media="all">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:600&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500&subset=latin,latin-ext,greek" rel="stylesheet" type="text/css">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">

    <!-- MathJax -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML" async></script>

    <!-- Custom JS -->
    <script type="text/javascript" src="{% static 'kvasaheim/functions.js' %}"></script>
    {% block customhead %}
    {% endblock %}
</head>
<body>
    <div class="outerBody">
        <div class="headerBar">
            <div class="navBar">
                <ul class="nav">
                    <li class="nav-item">You are here:</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:home' %}">Project Scarlet</li></a>
                    {% block nav %}
                    {% endblock %}
                </ul>
            </div>
            <div class="userBar">
                <ul class="nav">
                    {% if user.is_authenticated %}
                    {% if user.is_staff %}<li class="nav-item"><a href="{% url 'admin:index' %}">Admin</a></li>{% endif %}
                    <li class="nav-item"><a href="{% url 'kvasaheim:user_profile' user.username %}">{{ user.first_name }}</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:logout' %}">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'social:begin' 'google-oauth2' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>

        <div class="innerBody">
            <div class="header">
                <h1>Sample Statistics</h1>
            </div>
            <div class="headerImage"></div>
            <div class="content">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
    <div class="footerBar">
        © Ole J. Forsberg, Ph.D. {% now "Y" %}. All rights reserved.
    </div>
</body>
</html>

kvasaheim/templates/kvasaheim/categorical_problem_answer.html
{% extends 'kvasaheim/base.html' %}

{% block nav %}
{% with category=problem.category %}
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:home' category.id %}">{{ category }}</a></li>
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:problem_detail' problem.id %}" active>{{ problem.title }}</a></li>
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:problem_answer' problem.id answer.id %}" active>Answer</a></li>
{% endwith %}
{% endblock %}

{% block content %}
<h1>{{ problem.title }}</h1>
<h2>Submitted {{ answer.date }}</h2>
<h3>{{ answer.problem.numbers }}</h3>
{% if answer.problem.categorical_list %}
<h3>{{ answer.problem.categorical_list }}</h3>
{% endif %}
<p>Answered: {{ answer.answer }} {% if answer.correct %}CORRECT{% else %}INCORRECT</p>
<p>Solution: {{ answer.problem.answer }}</p>
<p>Retry: <a href="{% url 'kvasaheim:problem_detail' pk=answer.problem.problem.id ipk=answer.problem.id %}">This Problem</a> or <a href="{% url 'kvasaheim:problem_detail' pk=answer.problem.problem.id %}">Problems Like This</a></p>{% endif %}
<br><br>
{% endblock %}

kvasaheim/templates/kvasaheim/categorical_problem_detail.html
{% extends 'kvasaheim/base.html' %}

{% block title %}{{ problem.title }} - {% endblock %}

{% block customhead %}
    <script>
        /** .replace
          * This function replaces the @notation built for database parsing 
          * with its Django template parts in all html tags with the .replace
          * class. To define a new notation, add the following line before the
          * line "$(this).html(text);".
          *     text = text.replace(/(@<new_notation>)/g, '<new_string>')
          * Be careful of new notations that contain all or part of another
          * notation at its beginning. See @length1 and @length below.
          */
        $(function() {
            $('.replace').each(function() {
                // Assume set is [1,2,3,4,5]
                // $(this).html() gets the text with html tags to preserve formatting
                // @list replaces with '1, 2, 3, 4, 5'
                var text = $(this).html().replace(/(@list)/g, '{{ instance.numbers }}');
                text = text.replace(/(@catlist)/g, '{{ instance.second_numbers }}')
                // @length1 replaces with len(set)+1 == '6'
                // note: length1 needs to gets replaced before length, just as "mathematics" would need to get replaced before "math", else we are left with '1' or 'ematics'
                text = text.replace(/(@length1)/g, '{{ instance.numbers_list|length|add:"1" }}');
                text = text.replace(/(@catlength1)/g, '{{ instance.second_numbers_list|length|add:"1" }}');
                // @length replaces with len(set) == '5' 
                text = text.replace(/(@length)/g, '{{ instance.numbers_list|length }}');
                text = text.replace(/(@catlength)/g, '{{ instance.second_numbers_list|length }}');
                // @addition replaces with '1 + 2 + 3 + 4 + 5'
                text = text.replace(/(@addition)/g, '{{ instance.numbers_list|join:" + " }}');
                text = text.replace(/(@cataddition)/g, '{{ instance.second_numbers_list|join:" + " }}');
                // @multiplication replaces with '1 * 2 * 3 * 4 * 5'
                text = text.replace(/(@multiplication)/g, '{{ instance.numbers_list|join:" * " }}');
                text = text.replace(/(@catmultiplication)/g, '{{ instance.second_numbers_list|join:" * " }}');
                // @subtraction replaces with '1 - 2 - 3 - 4 - 5'
                text = text.replace(/(@subtraction)/g, '{{ instance.numbers_list|join:" - " }}');
                text = text.replace(/(@catsubtraction)/g, '{{ instance.second_numbers_list|join:" - " }}');
                // @division replaces with '1 ÷ 2 ÷ 3 ÷ 4 ÷ 5'
                text = text.replace(/(@division)/g, '{{ instance.numbers_list|join:" ÷ " }}');
                text = text.replace(/(@catdivision)/g, '{{ instance.second_numbers_list|join:" ÷ " }}');
                // @breaks replaces with '1<br>2<br>3<br>4<br>5'
                // used to make a vertical list
                text = text.replace(/(@breaks)/g, '{{ instance.numbers_list|join:"<br>" }}');
                text = text.replace(/(@catbreaks)/g, '{{ instance.second_numbers_list|join:"<br>" }}');
                // @sum replaces with '15' == sum(set)
                text = text.replace(/(@sum)/g, '{{ list_sum }}');
                text = text.replace(/(@catsum)/g, '{{ second_list_sum }}');
                // @answer replaces with the answer to the problem // for mean on set, this would be 3 == sum(set)/len(set) == 15/5
                text = text.replace(/(@answer)/g, '{{ instance.answer }}');
                // this does the actual replacing, keeping the html tags
                $(this).html(text);
            });
        });
    </script>
{% endblock %}

{% block nav %}
{% with category=problem.category %}
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:home' category.id %}">{{ category }}</a></li>
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:problem_detail' problem.id %}" active>{{ problem.title }}</a></li>
{% endwith %}
{% endblock %}

{% block content %}
<h1>{{ problem.title }}</h1>
<h2>The Problem</h2>
<p>{{ problem.text|safe }}</p>
<blockquote>
    {{ instance.numbers }}
    {{ instance.categorical_list }}
</blockquote>


<h2>Your Answer</h2>
{% if user.is_authenticated %}
<p>In the box below, please enter your guess for the data given above, then click on the “Check your answer!” button. Please round your answer to the <b>ten-thousandths place.</b></p>
<div class="guessRegion">
    <form action="{% url 'kvasaheim:problem_detail' problem.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="problem_instance" id="problem_instance" value="{{ instance.pk }}">
        {{ form.answer.errors }}
        <label for="{{ form.answer.id_for_label }}">Answer</label>
        {{ form.answer }}
        <input type="submit" value="Check your answer!">
    </form>
</div>
{% else %}
<p>Please <a href="{% url 'login' %}">login</a> to answer!</p>
{% endif %}

<h2>Assistance</h2>
<!-- Show the Formula -->
<div id="showFormula" style="display:block;">
    <p class="bodytextno"><span title="Click to show the formula" onclick="toggleFormula();" style="text-decoration:underline; cursor:pointer;">Show Formula</span></p>
</div>

<div id="hideFormula" style="display: none; padding-bottom: 3em;">
    <p class="bodytextno"><span title="Click to hide the formula" onclick="toggleFormula();" style="text-decoration:underline; cursor:pointer;">Hide Formula</span></p>
  
    <span class="replace">{{ problem.formula|safe }}</span>
    </div>
</div>

<!-- Show the solution -->
<div id="showSolution" style="display:block;">
    <p class="bodytextno"><span title="Click to show the solution" onclick="toggleSolution();" style="text-decoration:underline; cursor: pointer;">Show Solution</span></p>
</div>

<div id="hideSolution" style="display: none; padding-bottom: 3em;">
    <p class="bodytextno"><span title="Click to hide the solution" onclick="toggleSolution();" style="text-decoration:underline; cursor:pointer;">Hide Solution</span></p>

    <div style="margin:0 0 2em 2em;">
    <span class="replace">{{ problem.solution|safe }}</span>
    </div>
</div>

<!-- Show the R code -->
<div id="showR" style="display: block;">
    <p class="bodytextno"><span title="Click to show the R code" onclick="toggleR();" style="text-decoration:underline; cursor: pointer;">Show the R Code</span></p>
</div>    
    
<div id="hideR" style="display: none; padding-bottom: 3em;">
    <p class="bodytextno"><span title="Click to hide the R Code" onclick="toggleR();" style="text-decoration:underline; cursor:pointer;">Hide the R Code</span></p>
    <p class="bodytextno">Copy and paste the following code into your R script window, then run it from there.</p>
    <span class="replace">{{ problem.rcode|safe }}</span>
</div>

<!-- Show the Excel code -->
<div id="showExcel" style="display: block;">
    <p class="bodytextno"><span title="Click to show the Excel code" onclick="toggleExcel();" style="text-decoration:underline; cursor: pointer;">Show the Excel Code</span></p>
</div>

<div id="hideExcel" style="display: none; padding-bottom: 3em;">
    <p class="bodytextno"><span title="Click to hide the Excel Code" onclick="toggleExcel();" style="text-decoration:underline; cursor:pointer;">Hide the Excel Code</span></p>
    <p class="bodytextno">Copy and paste the following code into your Excel spreadsheet window, making sure your cursor is in <code>A1</code> when you paste.</p>
    <span class="replace">{{ problem.excel|safe }}</span>
</div>
{% endblock %}

kvasaheim/templates/kvasaheim/home.html
{% extends 'kvasaheim/base.html' %}
{% block nav %}
                    {% if rpk %}
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:home' rpk=rpk %}" active>{{ realms.first }}</a></li>
                    {% endif %}
                    {% if cpk %}
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:home' cpk=cpk %}" active>{{ categories.first }}</a></li>
                    {% endif %}
{% endblock %}

{% block content %}
{% for realm in realms %}
<h1>{{ realm.title }}</h1>
<p>{{ realm.text }}</p>
<ul>
    {% for category in categories %}
    {% ifequal category.realm realm %}
    <h2>{{ category.title }}</h2>
    <ul class="problemList">
    	{% for problem in problems %}
	    	{% ifequal problem.category category %}
	        <li><a href="{% url 'kvasaheim:problem_detail' pk=problem.pk %}">{{ problem.title }}</a></li>
	        {% endifequal %}
        {% empty %}
	        <p>No problems published in this category.</p>
        {% endfor %}
    </ul>
    {% endifequal %}
    {% empty %}
    <h2>No categories published in this realm.</h2>
    {% endfor %}
</ul>
{% empty %}
<h1>All realms offline.</h1>
{% endfor %}
{% endblock %}

kvasaheim/templates/kvasaheim/problem_answer.html
{% extends 'kvasaheim/base.html' %}

{% block nav %}
{% with realm=problem.category.realm %}
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:home' realm.id %}">{{ realm }}</a></li>
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:problem_detail' problem.id %}" active>{{ problem.title }}</a></li>
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:problem_answer' problem.id answer.id %}" active>Answer</a></li>
{% endwith %}
{% endblock %}

{% block content %}
<h1>{{ problem.title }}</h1>
<h2>Submitted {{ answer.date }}</h2>
<h3>{{ answer.problem.numbers }}</h3>
{% if answer.problem.second_numbers %}
<h3>{{ answer.problem.second_numbers }}</h3>
{% endif %}
<p>Answered: {{ answer.answer }} {% if answer.correct %}<span class="correct">&#10003;</span></p>{% else %}<span class="incorrect">&#10005;</span></p>
<p>Solution: {{ answer.problem.answer }}</p>
<p>Retry: <a href="{% url 'kvasaheim:problem_detail' pk=answer.problem.problem.id ipk=answer.problem.id %}">This Problem</a> or <a href="{% url 'kvasaheim:problem_detail' pk=answer.problem.problem.id %}">Problems Like This</a></p>{% endif %}
<br><br>
{% endblock %}

kvasaheim/templates/kvasaheim/user_profile.html
{% extends 'kvasaheim/base.html' %}
{% block nav %}
                    <li class="nav-item">»</li>
                    <li class="nav-item">User</li>
                    <li class="nav-item">»</li>
                    <li class="nav-item"><a href="{% url 'kvasaheim:user_profile' u.username %}" active>{{ u.username }}</a></li>
{% endblock %}

{% block content %}
<h1 class="user">{{ u.first_name }} {{ u.last_name }} ({{ u.username }})</h1>
<h2>Answers</h2>
{% for category in categories %}
<h1 class="center"><a href="{% url 'kvasaheim:home' cpk=category.id %}">{{ category }}</a></h1>
{% for problem in problems %}
{% if problem.category == category %}
<h1 class="center">{{ problem.title }}</h1>
<div class="results">
    {% for answer in answers %}
    {% if answer.problem.problem == problem %}
    <div class="result">
        <div class="aligned">
            <h2>{{ answer.problem.problem.title }} of <a href="{% url 'kvasaheim:problem_detail' pk=answer.problem.problem.id ipk=answer.problem.id %}">{{ answer.problem.numbers }}</a></h2>
            <h3>{{ answer.date }}</h3>
            <p><span class="info">Answered:</span> {{ answer.answer }} {% if answer.correct %} <span class="correct">&#10003;</span></p>{% else %}<span class="incorrect">&#10005;</span></p>
            <p><span class="info">Solution:</span> {{ answer.problem.answer }}</p>
            <p><span class="info">Retry:</span> <a href="{% url 'kvasaheim:problem_detail' pk=answer.problem.problem.id ipk=answer.problem.id %}">This Problem</a> or <a href="{% url 'kvasaheim:problem_detail' pk=answer.problem.problem.id %}">Problems Like This</a></p>{% endif %}
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
    {% endif %}
    {% endfor %}
    {% endfor %}
{% endblock %}